import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/nav/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { AuthProvider } from "@/components/AuthProvider";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "Chat harbor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className="flex flex-col min-h-screen">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children} <Footer />
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
